variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Container-Scanning.gitlab-ci.yml

build:
  image: docker:stable
  stage: build
  services:
    - docker:dind
  variables:
    IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
  script:
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $IMAGE .
    - docker push $IMAGE

flake8:
  stage: test
  image: raackley/gitlab-runner
  script: flake8
  tags: ["docker"]