#!/bin/sh

docker run --rm -e RHD_USERNAME=$RHD_USERNAME \
-e RHD_PASSWORD=$RHD_PASSWORD \
-e RHD_CLIENT_ID=$RHD_CLIENT_ID \
-e RHD_CLIENT_SECRET=$RHD_CLIENT_SECRET \
-e RHD_EXPIRATION_DAYS=$RHD_EXPIRATION_DAYS \
-e RHD_MODE=$RHD_MODE \
-e RHD_OVERWRITE_MESSAGE=$RHD_OVERWRITE_MESSAGE \
$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
